name: Keep Supabase Awake

on:
  schedule:
    - cron: "0 12 * * *"   # Runs every day at 12:00 UTC
  workflow_dispatch:       # Lets you run it manually

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl request to Supabase
        run: |
          curl -s https://mrytwyoildhgbayfoddc.supabase.co
